Stop if -C link-args is overridden.

diff --git a/tests_profile b/tests_profile
--- a/tests_profile
+++ b/tests_profile
@@ -43,6 +43,11 @@ export RUST_LIB_DIR=$(rustup run ${RUST_VERSION} rustc --print sysroot)/lib
 echo "RUST_LIB_DIR: ${RUST_LIB_DIR}"
 
 # Linking options with additional paths for the application and tests.
-# Note: this may override previous `-C link-args` if it appears in RUSTFLAGS before.
-export RUSTFLAGS="${RUSTFLAGS:-} -C link-args=-Wl,-rpath,${RUST_LIB_DIR},-rpath,${JAVA_LIB_DIR}"
+# This may override previous `-C link-args` if it appears in RUSTFLAGS before.
+RUSTFLAGS="${RUSTFLAGS:-}"
+if [[ $RUSTFLAGS = *"-C link-args="* ]]; then
+    echo "Error: the '-C link-args' RUSTFLAGS option will be overriden. Merge is not yet supported."
+    exit 1
+fi
+export RUSTFLAGS="${RUSTFLAGS} -C link-args=-Wl,-rpath,${RUST_LIB_DIR},-rpath,${JAVA_LIB_DIR}"
 echo "RUSTFLAGS=${RUSTFLAGS}"
